### ISSUE TITLE
MSVC can not link to boost correctly

### ISSUE THREAD

**Issue by nickoe** [cbernardo/libIGES#13]
According to the discussion in #10 about the boost issues during linking, it should be required to add the define `BOOST_ALL_NO_LIB` in the add_definitions macro under the MSVC check.

I have used that with MSVC and it works. This seems to be the last issue to make libiges build on the KiCad Jenkins server. I post this issue because I am not with my dev machine now, and noting that @cbernardo did not need to do so according to https://github.com/cbernardo/libIGES/issues/10#issuecomment-109809381. Which I think is strange. The boost build I tested against is the one from the Jenkins, which is also built with b2.

http://stackoverflow.com/questions/4736877/how-to-link-boost-in-a-dependant-static-library

**Comment by cbernardo** [comment]
I checked for MSVC and added the preprocessor definitions:
BOOST_ALL_DYN_LINK
BOOST_NO_EXCEPTIONS

However, when I was playing with the static libIGES and MSVC (version 12 = MSVC 2013) I didn't need to define anything.

**Comment by nickoe** [comment]
I don't know what is most appropriate or correct, but at least it builds on Jenkins now. I guess that commit 9dc98fa44d46a6201e5e97169dde52a3b4464529 fixes this issue then.
