### ISSUE TITLE
Patch step for 'sisl' fails, missing patch

### ISSUE THREAD

**Issue by nickoe** [cbernardo/libIGES#5]
The patch step for 'sisl' fails because the `libIGES/src/patches/sisl.patch` is missing

**Comment by nickoe** [comment]
If that patch is to make sisl build as a shared lib, I think one could pass `-DBUILD_SHARED_LIBS=true` to cmake. I have not tested this though.

**Comment by ilockerstien** [comment]
I'm a noob at make files but I tried 'sudo cmake -DBUILD_SHARED_LIBS=true' followed by 'make'.
This didn't work for me.  Did I follow your suggestion correctly?  Should I have edited something to remove references to the patches directory?

**Comment by nickoe** [comment]
That is not correct. You should not use sudo on cmake, it should be run by the user. Only the `make install` should be run as the root user, that is if you need to where it installs to the system files.

Try:
    git clean -fdx
    git pull
    mkdir build
    cd build
    cmake ../src
    make
