### ISSUE TITLE
MSVC do not like the #warning preprocessor command

### ISSUE THREAD

**Issue by nickoe** [cbernardo/libIGES#9]
When building with the MSVC it will fail with the following error.

`fatal error C1021: invalid preprocessor command 'warning'`

Some suggestions to fix this and still have the opportunity to write warning and errors is to have a look at theese two suggestions:
http://stackoverflow.com/questions/471935/user-warnings-on-msvc-and-gcc
http://stackoverflow.com/questions/6438468/force-warning-error

**Comment by cbernardo** [comment]
I will just comment these out and put in some other marker, or consider placing a definition in "error_macros.h" which uses the #pragma comment for MSVC and "#warning" for gcc and others. I hate MS #pragmas (or any #pragma for that matter).

**Comment by nickoe** [comment]
Also be aware og the #error one.  I see you have uncommented the #warning ones in 53914c9d42fe73671bc80f19316f8999b13eb5ec.
